version: '3.0'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: on-failure
    ports:
      - 90:80
    volumes:
      - ./web:/var/www:rw
      - ./logs/nginx:/var/log/nginx:rw
    depends_on:
      - php
    networks:
      - backend

  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./web:/var/www
    ports:
      - "9000:9000"
    environment:
        ENV_DEV: ${ENV_DEV}
        MYSQL_DB: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    volumes:
#      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - backend

networks:
  backend: